--liquibase formatted sql logicalFilePath:db/changelog/migration-oracle-1.0-initial-schema.sql

--changeset lymar-sa:RISE-1-1
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'DEPARTMENT_TYPE'
CREATE TABLE DEPARTMENT_TYPE
(
    ID BIGINT NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    CREATED_DATE DATE NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    DELETED_DATE DATE,
    DESCRIPTION VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255),
    UPDATED_DATE DATE,
    UUID VARCHAR(255) NOT NULL,
    CONSTRAINT DEPARTMENT_TYPE_PK PRIMARY KEY (id)
);
CREATE SEQUENCE DEPARTMENT_TYPE_SEQUENCE START WITH 1 INCREMENT BY 1000;
--rollback not required

--changeset lymar-sa:RISE-1-2
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'DEPARTMENT'
CREATE TABLE DEPARTMENT
(
    ID BIGINT NOT NULL,
    CREATED_DATE DATE NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    DELETED_DATE DATE,
    DESCRIPTION VARCHAR(255),
    TITLE VARCHAR(255) NOT NULL,
    UPDATED_DATE DATE,
    UUID VARCHAR(255) NOT NULL,
    DEPARTMENT_TYPE_ID BIGINT NOT NULL,
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY (ID),
    CONSTRAINT DEPARTMENT_DEPARTMENT_TYPE_FK FOREIGN KEY (DEPARTMENT_TYPE_ID)
        REFERENCES DEPARTMENT_TYPE (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE SEQUENCE DEPARTMENT_SEQUENCE START WITH 1 INCREMENT BY 1000;
--rollback not required

--changeset lymar-sa:RISE-1-3
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'TEAM'
CREATE TABLE TEAM
(
    ID BIGINT NOT NULL,
    CREATED_DATE DATE NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    DELETED_DATE DATE,
    DESCRIPTION VARCHAR(255),
    TITLE VARCHAR(255) NOT NULL,
    UPDATED_DATE DATE,
    UUID VARCHAR(255) NOT NULL,
    DEPARTMENT_ID BIGINT NOT NULL,
    CONSTRAINT TEAM_PK PRIMARY KEY (ID),
    CONSTRAINT TEAM_DEPARTMENT_FK FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE SEQUENCE TEAM_SEQUENCE START WITH 1 INCREMENT BY 1000;
--rollback not required

--changeset lymar-sa:RISE-1-4
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'PROJECT'
CREATE TABLE PROJECT
(
    ID BIGINT NOT NULL,
    CREATED_DATE DATE NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    DELETED_DATE DATE,
    DESCRIPTION VARCHAR(255),
    IS_DONE BOOLEAN NOT NULL,
    END_DATE DATE,
    START_DATE DATE NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    PROJECT_TYPE VARCHAR(255),
    UPDATED_DATE DATE,
    UUID VARCHAR(255) NOT NULL,
    TEAM_ID BIGINT NOT NULL,
    CONSTRAINT PROJECT_PK PRIMARY KEY (ID),
    CONSTRAINT PROJECT_TEAM_FK FOREIGN KEY (TEAM_ID)
        REFERENCES TEAM (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE SEQUENCE PROJECT_SEQUENCE START WITH 1 INCREMENT BY 1000;
--rollback not required

--changeset lymar-sa:RISE-1-5
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'GOAL'
CREATE TABLE GOAL
(
    ID BIGINT NOT NULL,
    CREATED_DATE DATE NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    DELETED_DATE DATE,
    DESCRIPTION VARCHAR(255) NOT NULL,
    IS_DONE BOOLEAN NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    UPDATED_DATE DATE,
    UUID VARCHAR(255) NOT NULL,
    PROJECT_ID BIGINT NOT NULL,
    CONSTRAINT GOAL_PK PRIMARY KEY (id),
    CONSTRAINT GOAL_PROJECT_FK FOREIGN KEY (PROJECT_ID)
        REFERENCES PROJECT (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE SEQUENCE GOAL_SEQUENCE START WITH 1 INCREMENT BY 1000;
--rollback not required

--changeset lymar-sa:RISE-1-6
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'EMPLOYER'
CREATE TABLE EMPLOYER
(
    ID BIGINT NOT NULL,
    CREATED_DATE DATE NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    DELETED_DATE DATE,
    DISMISSAL_DATE DATE,
    EMPLOYMENT_DATE DATE NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    SECOND_NAME VARCHAR(255) NOT NULL,
    THIRD_NAME VARCHAR(255),
    EMPLOYER_TYPE VARCHAR(255) NOT NULL,
    UPDATED_DATE DATE,
    UUID VARCHAR(255) NOT NULL,
    TEAM_ID BIGINT NOT NULL,
    CONSTRAINT EMPLOYER_PK PRIMARY KEY (ID),
    CONSTRAINT EMPLOYER_TEAM_FK FOREIGN KEY (TEAM_ID)
        REFERENCES TEAM (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE SEQUENCE EMPLOYER_SEQUENCE START WITH 1 INCREMENT BY 1000;
--rollback not required

--changeset lymar-sa:RISE-1-7
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'TASK'
CREATE TABLE TASK
(
    ID BIGINT NOT NULL,
    CREATED_DATE DATE NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    DELETED_DATE DATE,
    DESCRIPTION VARCHAR(255) NOT NULL,
    IS_DONE BOOLEAN NOT NULL,
    END_DATE DATE,
    PRIORITY_TYPE VARCHAR(255) NOT NULL,
    START_DATE DATE NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    UPDATED_DATE DATE,
    UUID VARCHAR(255) NOT NULL,
    EMPLOYER_ID BIGINT NOT NULL,
    GOAL_ID BIGINT NOT NULL,
    CONSTRAINT TASK_PK PRIMARY KEY (ID),
    CONSTRAINT TASK_GOAL_FK FOREIGN KEY (GOAL_ID)
        REFERENCES GOAL (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT TASK_EMPLOYER_FK FOREIGN KEY (EMPLOYER_ID)
        REFERENCES EMPLOYER (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE SEQUENCE TASK_SEQUENCE START WITH 1 INCREMENT BY 1000;
--rollback not required

--changeset lymar-sa:RISE-1-8
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'SALARY'
CREATE TABLE SALARY
(
    ID BIGINT NOT NULL,
    CREATED_DATE DATE NOT NULL,
    CURRENCY_TYPE VARCHAR(255) NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    DELETED_DATE DATE,
    SALARY BIGINT NOT NULL,
    UPDATED_DATE DATE,
    UUID VARCHAR(255) NOT NULL,
    EMPLOYER_ID BIGINT NOT NULL,
    CONSTRAINT SALARY_PK PRIMARY KEY (ID),
    CONSTRAINT SALARY_EMPLOYER_FK FOREIGN KEY (EMPLOYER_ID)
        REFERENCES EMPLOYER (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE SEQUENCE SALARY_SEQUENCE START WITH 1 INCREMENT BY 1000;
--rollback not required

--changeset lymar-sa:RISE-1-9
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'CONTACT'
CREATE TABLE CONTACT
(
    ID BIGINT NOT NULL,
    CREATED_DATE DATE NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    DELETED_DATE DATE,
    EMAIL VARCHAR(255),
    PHONE VARCHAR(255),
    UPDATED_DATE DATE,
    UUID VARCHAR(255) NOT NULL,
    EMPLOYER_ID BIGINT NOT NULL,
    CONSTRAINT CONTACT_PK PRIMARY KEY (ID),
    CONSTRAINT CONTACT_EMPLOYER_FK FOREIGN KEY (EMPLOYER_ID)
        REFERENCES EMPLOYER (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE SEQUENCE CONTACT_SEQUENCE START WITH 1 INCREMENT BY 1000;
--rollback not required

--changeset lymar-sa:RISE-1-10
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'COMPETENCE'
CREATE TABLE COMPETENCE
(
    ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    CREATED_DATE DATE NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    DELETED_DATE DATE,
    EXPERIENCE BIGINT NOT NULL,
    TECHNOLOGY VARCHAR(255),
    TYPE INTEGER NOT NULL,
    UPDATED_DATE DATE,
    UUID VARCHAR(255) NOT NULL,
    EMPLOYER_ID BIGINT NOT NULL,
    CONSTRAINT COMPETENCE_PK PRIMARY KEY (ID),
    CONSTRAINT COMPETENCE_EMPLOYER_FK FOREIGN KEY (EMPLOYER_ID)
        REFERENCES EMPLOYER (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE SEQUENCE COMPETENCE_SEQUENCE START WITH 1 INCREMENT BY 1000;
--rollback not required

--changeset lymar-sa:RISE-1-11
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'AWARD'
CREATE TABLE AWARD
(
    ID BIGINT NOT NULL,
    CREATED_DATE DATE NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    DELETED_DATE DATE,
    DESCRIPTION VARCHAR(255),
    REASON VARCHAR(255),
    RECEIPT_DATE DATE,
    TITLE VARCHAR(255) NOT NULL,
    UPDATED_DATE DATE,
    UUID VARCHAR(255) NOT NULL,
    EMPLOYER_ID BIGINT NOT NULL,
    CONSTRAINT AWARD_PK PRIMARY KEY (ID),
    CONSTRAINT AWARD_EMPLOYER_FK FOREIGN KEY (EMPLOYER_ID)
        REFERENCES EMPLOYER (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE SEQUENCE AWARD_SEQUENCE START WITH 1 INCREMENT BY 1000;
--rollback not required

--changeset lymar-sa:RISE-1-12
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'ADDRESS'
CREATE TABLE ADDRESS
(
    ID BIGINT NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    CREATED_DATE DATE NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    DELETED_DATE DATE,
    UPDATED_DATE DATE,
    UUID VARCHAR(255) NOT NULL,
    EMPLOYER_ID BIGINT NOT NULL,
    CONSTRAINT ADDRESS_PK PRIMARY KEY (ID),
    CONSTRAINT ADDRESS_EMPLOYER_FK FOREIGN KEY (EMPLOYER_ID)
        REFERENCES EMPLOYER (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE SEQUENCE ADDRESS_SEQUENCE START WITH 1 INCREMENT BY 1000;
--rollback not required

--changeset lymar-sa:RISE-1-13
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'TRAINING'
CREATE TABLE TRAINING
(
    ID BIGINT NOT NULL,
    CREATED_DATE DATE NOT NULL,
    CURRENCY_TYPE INTEGER NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    DELETED_DATE DATE,
    DESCRIPTION VARCHAR(255),
    END_DATE DATE NOT NULL,
    PRICE BIGINT NOT NULL,
    START_DATE DATE NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    UPDATED_DATE DATE,
    UUID VARCHAR(255) NOT NULL,
    EMPLOYER_ID BIGINT NOT NULL,
    CONSTRAINT TRAINING_PK PRIMARY KEY (ID),
    CONSTRAINT TRAINING_EMPLOYER_FK FOREIGN KEY (EMPLOYER_ID)
        REFERENCES EMPLOYER (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE SEQUENCE TRAINING_SEQUENCE START WITH 1 INCREMENT BY 1000;
--rollback not required

--changeset lymar-sa:RISE-2-1
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'DEPARTMENT_TYPE'
INSERT INTO  DEPARTMENT_TYPE (ID, UUID, TYPE, CODE, DESCRIPTION, CREATED_DATE, IS_DELETED, DELETED_DATE,  UPDATED_DATE) VALUES (1, 'department_type_uuid_1', 'IT', 'department.type.it', 'IT department', '2022-05-02 09:17:40.431', false, null, null);
INSERT INTO  DEPARTMENT_TYPE (ID, UUID, TYPE, CODE, DESCRIPTION, CREATED_DATE, IS_DELETED, DELETED_DATE,  UPDATED_DATE) VALUES (2, 'department_type_uuid_2', 'FINANCIAL', 'department.type.financial', 'Financial department', '2022-05-02 09:17:40.431', false, null, null);
INSERT INTO  DEPARTMENT_TYPE (ID, UUID, TYPE, CODE, DESCRIPTION, CREATED_DATE, IS_DELETED, DELETED_DATE,  UPDATED_DATE) VALUES (3, 'department_type_uuid_3', 'HR', 'department.type.hr', 'HR department', '2022-05-02 09:17:40.431', false, null, null);
INSERT INTO  DEPARTMENT_TYPE (ID, UUID, TYPE, CODE, DESCRIPTION, CREATED_DATE, IS_DELETED, DELETED_DATE,  UPDATED_DATE) VALUES (4, 'department_type_uuid_4', 'MARKETING', 'department.type.marketing', 'Marketing department', '2022-05-02 09:17:40.431', false, null, null);
INSERT INTO  DEPARTMENT_TYPE (ID, UUID, TYPE, CODE, DESCRIPTION, CREATED_DATE, IS_DELETED, DELETED_DATE,  UPDATED_DATE) VALUES (5, 'department_type_uuid_5', 'SALES', 'department.type.sales', 'Sales department', '2022-05-02 09:17:40.431', false, null, null);
INSERT INTO  DEPARTMENT (ID, UUID, TITLE, DESCRIPTION, CREATED_DATE, IS_DELETED, DELETED_DATE,  UPDATED_DATE, DEPARTMENT_TYPE_ID) VALUES (1, 'department_uuid_1', 'IT Department', 'Software development and maintenance', '2022-05-02 09:17:40.431', false, null, null, 1);
INSERT INTO  DEPARTMENT (ID, UUID, TITLE, DESCRIPTION, CREATED_DATE, IS_DELETED, DELETED_DATE,  UPDATED_DATE, DEPARTMENT_TYPE_ID) VALUES (2, 'department_uuid_2', 'Financial Department', 'Finance Department', '2022-05-02 09:17:40.431', false, null, null, 2);
INSERT INTO  DEPARTMENT (ID, UUID, TITLE, DESCRIPTION, CREATED_DATE, IS_DELETED, DELETED_DATE,  UPDATED_DATE, DEPARTMENT_TYPE_ID) VALUES (3, 'department_uuid_3', 'HR Department', 'Hiring employees', '2022-05-02 09:17:40.431', false, null, null, 3);
INSERT INTO  DEPARTMENT (ID, UUID, TITLE, DESCRIPTION, CREATED_DATE, IS_DELETED, DELETED_DATE,  UPDATED_DATE, DEPARTMENT_TYPE_ID) VALUES (4, 'department_uuid_4', 'Marketing Department', 'Marketing', '2022-05-02 09:17:40.431', false, null, null, 4);
INSERT INTO  DEPARTMENT (ID, UUID, TITLE, DESCRIPTION, CREATED_DATE, IS_DELETED, DELETED_DATE,  UPDATED_DATE, DEPARTMENT_TYPE_ID) VALUES (5, 'department_uuid_5', 'Sales Department', 'Sale of goods and turnover', '2022-05-02 09:17:40.431', false, null, null, 5);

--changeset lymar-sa:RISE-2-2
--preconditions onFail:MARK_RAN onError:HALT onUpdateSql:FAIL
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'ATTENDANCE'
CREATE TABLE ATTENDANCE (
     ID BIGINT NOT NULL,
     ARRIVAL_TIME TIMESTAMP,
     DEPARTURE_TIME TIMESTAMP,
     EMPLOYER_ID BIGINT NOT NULL,
     CONSTRAINT ATTENDANCE_PK PRIMARY KEY (ID),
     CONSTRAINT ATTENDANCE_EMPLOYER_FK FOREIGN KEY (EMPLOYER_ID)
         REFERENCES EMPLOYER (ID)
         ON UPDATE NO ACTION
         ON DELETE NO ACTION
);
CREATE SEQUENCE ATTENDANCE_SEQUENCE START WITH 1 INCREMENT BY 1000;